/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BotCard: typeof import('./components/BotCard.vue')['default']
    ContactInfoForm: typeof import('./components/ContactInfoForm.vue')['default']
    CreditCard: typeof import('./components/CreditCard.vue')['default']
    DestinationCard: typeof import('./components/DestinationCard.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    FoodAndActivities: typeof import('./components/FoodAndActivities.vue')['default']
    GenderSelect: typeof import('./components/GenderSelect.vue')['default']
    LandingCarousel: typeof import('./components/LandingCarousel.vue')['default']
    LandingChatBot: typeof import('./components/LandingChatBot.vue')['default']
    LandingDivider: typeof import('./components/LandingDivider.vue')['default']
    LandingFeature: typeof import('./components/LandingFeature.vue')['default']
    LandingFoodAndActivities: typeof import('./components/LandingFoodAndActivities.vue')['default']
    LandingFooter: typeof import('./components/LandingFooter.vue')['default']
    LandingMap: typeof import('./components/LandingMap.vue')['default']
    LandingSubscription: typeof import('./components/LandingSubscription.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    Payment: typeof import('./components/Payment.vue')['default']
    PersonalInfoForm: typeof import('./components/PersonalInfoForm.vue')['default']
    ProfileAvatar: typeof import('./components/ProfileAvatar.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
