/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactInfoForm: typeof import('./components/ContactInfoForm.vue')['default']
    GenderSelect: typeof import('./components/GenderSelect.vue')['default']
    PersonalInfoForm: typeof import('./components/PersonalInfoForm.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
